"""Generate sample contract PDFs for ContractSwarm demo."""

from fpdf import FPDF
import os

CONTRACTS_DIR = os.path.join(os.path.dirname(__file__), "..", "contracts")
os.makedirs(CONTRACTS_DIR, exist_ok=True)

CONTRACTS = [
    {
        "filename": "acme_corp_msa.pdf",
        "title": "MASTER SERVICES AGREEMENT",
        "client": "Acme Corporation",
        "sections": [
            ("1. SERVICES AND SCOPE", "Provider shall deliver cybersecurity compliance monitoring services as described in Exhibit A. Client expressly authorizes Provider to engage qualified third-party vendors, tools, and subprocessors - including AI-powered compliance and control-testing platforms - to assist in delivering the Services, provided such vendors maintain appropriate security certifications. Client may engage other vendors for complementary or similar services at its sole discretion."),
            ("2. DATA HANDLING AND SHARING", "2.1 Provider may process, analyze, and share Client Data with authorized third-party compliance tools and subprocessors solely for the purpose of delivering the Services, including automated control testing, SOX and SOC report generation, and compliance evaluation.\n\n2.2 All Client Data shall be stored and processed within data centers located in the continental United States.\n\n2.3 Provider shall maintain administrative, physical, and technical safeguards including AES-256 encryption at rest and in transit per 45 C.F.R. Section 164.312."),
            ("3. THIRD-PARTY VENDOR AUTHORIZATION", "3.1 Client acknowledges and consents that Provider may share Client Data with third-party software tools used to automate compliance testing, including tools that evaluate client-provided data against testing attributes and generate SOX or SOC reports.\n\n3.2 Provider shall ensure all third-party vendors execute agreements containing data protection obligations consistent with this Agreement and applicable law.\n\n3.3 Provider shall maintain a list of third-party vendors and make it available to Client upon request."),
            ("4. HIPAA COMPLIANCE", "4.1 Provider is a Business Associate as defined under HIPAA (45 C.F.R. Parts 160 and 164). This Section constitutes a Business Associate Agreement per 45 C.F.R. Section 164.502(e) and Section 164.504(e).\n\n4.2 Provider shall not use or disclose PHI other than as permitted by this Agreement or as required by law.\n\n4.3 Provider shall implement safeguards per Subpart C of 45 C.F.R. Part 164 including risk analysis, audit controls, access controls, and AES-256 encryption.\n\n4.4 Provider shall report any Breach of Unsecured PHI within thirty (30) calendar days of discovery.\n\n4.5 Provider shall ensure subcontractors execute Business Associate Agreements per 45 C.F.R. Section 164.504(e).\n\n4.6 Upon termination, Provider shall return or destroy all PHI within thirty (30) calendar days."),
            ("5. CCPA COMPLIANCE", "5.1 Provider is a Service Provider per Cal. Civ. Code Section 1798.140(ag).\n\n5.2 Provider shall not sell or share Personal Information. Provider shall not use Personal Information outside the direct business relationship or for any commercial purpose other than providing the Services.\n\n5.3 Provider shall assist Client with consumer requests within ten (10) business days.\n\n5.4 Upon termination, Provider shall delete all Personal Information within thirty (30) calendar days."),
            ("6. FEES AND TERM", "6.1 Client shall pay Provider an annual fee of USD 150,000, invoiced quarterly.\n\n6.2 Initial term of three (3) years with automatic one-year renewals.\n\n6.3 Either party may terminate for material breach upon thirty (30) days written notice."),
        ],
    },
    {
        "filename": "globex_dpa.pdf",
        "title": "DATA PROCESSING AGREEMENT",
        "client": "Globex Industries",
        "sections": [
            ("1. SCOPE", "This Data Processing Agreement governs the processing of personal data by Provider on behalf of Client in connection with the cybersecurity services described in the Master Services Agreement dated January 15, 2024. To the extent Provider processes Protected Health Information as defined by HIPAA or Personal Information as defined by the CCPA, the applicable provisions of this Agreement shall govern."),
            ("2. DATA CATEGORIES", "Provider shall process the following categories of personal data: employee names, email addresses, IP addresses, network access logs, device identifiers, and security event data. \"Protected Health Information\" or \"PHI\" shall have the meaning set forth in 45 C.F.R. Section 160.103. \"Personal Information\" shall have the meaning set forth in Cal. Civ. Code Section 1798.140(v)."),
            ("3. PROCESSING RESTRICTIONS", "3.1 Provider shall process personal data solely as instructed by Client and only for the purpose of delivering the Services under this Agreement. Provider shall not use personal data for any secondary purpose, including internal analytics or benchmarking.\n\n3.2 Provider shall ensure that all persons authorized to process personal data have committed themselves to confidentiality obligations no less restrictive than those contained herein.\n\n3.3 Provider may engage subprocessors to assist in delivering the Services upon fifteen (15) business days' prior written notice to Client. Client may object in writing during the notice period; absent objection, approval is deemed granted. Each subprocessor shall execute a Business Associate Agreement as required by 45 C.F.R. Section 164.504(e) and a CCPA-compliant service provider agreement containing data protection obligations no less protective than this Agreement."),
            ("4. DATA RESIDENCY", "4.1 All personal data, including PHI and Personal Information, shall be stored and processed exclusively within data centers located in the continental United States. Provider shall not transfer personal data outside the United States without Client's prior written consent.\n\n4.2 Client acknowledges that Provider's primary data centers are located in the United States."),
            ("5. SECURITY MEASURES", "Provider shall implement appropriate administrative, physical, and technical safeguards to ensure a level of security appropriate to the risk, including:\n(a) encryption of personal data at rest and in transit using AES-256 or equivalent;\n(b) risk analysis procedures per 45 C.F.R. Section 164.308(a)(1);\n(c) audit controls per 45 C.F.R. Section 164.312(b);\n(d) access controls per 45 C.F.R. Section 164.312(a);\n(e) the ability to restore availability and access to personal data in a timely manner;\n(f) a process for regularly testing and evaluating effectiveness of security measures."),
            ("6. HIPAA BUSINESS ASSOCIATE PROVISIONS", '6.1 To the extent Provider creates, receives, maintains, or transmits PHI on behalf of Client, Provider is a "Business Associate" as defined under HIPAA (45 C.F.R. Parts 160 and 164). This Section constitutes a Business Associate Agreement as required by 45 C.F.R. Section 164.502(e) and Section 164.504(e).\n\n6.2 Provider shall not use or disclose PHI other than as permitted by this Agreement or as required by law. Permitted uses include performance of the Services and Provider\'s proper management and administration where required by law.\n\n6.3 Provider shall comply with Subpart C of 45 C.F.R. Part 164 with respect to electronic PHI and implement the safeguards described in Section 5.\n\n6.4 Provider shall report any Breach of Unsecured PHI (as defined in 45 C.F.R. Section 164.402) or Security Incident to Client without unreasonable delay and within thirty (30) calendar days of discovery. Reports shall include: (a) identification of affected individuals; (b) description of the incident; (c) types of PHI involved; (d) recommended protective steps; and (e) corrective actions taken.\n\n6.5 Provider shall ensure subcontractors that access PHI execute Business Associate Agreements with identical restrictions per 45 C.F.R. Section 164.504(e)(1)(ii)(B).\n\n6.6 Provider shall support Client\'s obligations for individual access (45 C.F.R. Section 164.524), amendment (45 C.F.R. Section 164.526), and accounting of disclosures (45 C.F.R. Section 164.528).\n\n6.7 Provider shall make its practices, books, and records available to the Secretary of HHS for compliance determination.\n\n6.8 Upon termination, Provider shall return or destroy all PHI within thirty (30) calendar days and certify destruction in writing. If infeasible, protections of this Agreement extend to retained PHI.'),
            ("7. CCPA SERVICE PROVIDER PROVISIONS", '7.1 To the extent Provider processes Personal Information subject to the CCPA, Provider is a "Service Provider" as defined in Cal. Civ. Code Section 1798.140(ag).\n\n7.2 Provider certifies compliance with: (a) Provider shall not sell or share Personal Information as defined by the CCPA; (b) Provider shall not retain, use, or disclose Personal Information for any purpose other than performing the Services, including any commercial purpose; (c) Provider shall not retain, use, or disclose Personal Information outside the direct business relationship between Provider and Client; (d) Provider shall not combine Personal Information with information from other sources except as permitted by Cal. Civ. Code Section 1798.140(e)(6) and (e)(7).\n\n7.3 Provider shall assist Client in responding to verifiable consumer requests (know, delete, correct) within ten (10) business days. Provider shall delete Personal Information and direct subprocessors to do the same upon Client\'s request, unless retention is permitted under Cal. Civ. Code Section 1798.105(d).\n\n7.4 Provider shall notify Client within five (5) business days if it can no longer meet CCPA obligations. Client may take reasonable steps to remediate unauthorized use.\n\n7.5 Provider shall allow compliance audits not more than once per twelve (12) months.'),
            ("8. BREACH NOTIFICATION", "Provider shall notify Client of any personal data breach, Breach of Unsecured PHI (45 C.F.R. Section 164.402), or Security Incident without unreasonable delay and within thirty (30) calendar days of discovery. Notification shall include: (a) the nature and scope of the breach; (b) identification of affected individuals; (c) the types of data involved; (d) recommended protective steps for affected individuals; (e) corrective actions taken or proposed by Provider."),
            ("9. FEES", "The annual fee for the data processing services described in this Agreement shall be USD 85,000, invoiced quarterly in advance. Payment is due within thirty (30) days of invoice date."),
            ("10. AUDIT RIGHTS", "Provider shall make available to Client all information necessary to demonstrate compliance with this Agreement, including HIPAA and CCPA obligations, and shall allow for and contribute to audits conducted by Client or an auditor mandated by Client, not more than once per twelve (12) month period unless a breach or compliance concern necessitates an immediate assessment."),
        ],
    },
    {
        "filename": "initech_services.pdf",
        "title": "SERVICE AGREEMENT",
        "client": "Initech Solutions",
        "sections": [
            ("1. SERVICES", "Provider shall provide continuous security monitoring, vulnerability assessment, and compliance reporting services for Client's cloud infrastructure. Client authorizes Provider to use third-party compliance automation tools, including AI-powered platforms for SOX and SOC control testing, to deliver the Services efficiently."),
            ("2. DATA HANDLING", "2.1 Provider shall process Client Data for the purpose of providing the Services. Provider may share Client Data with authorized third-party compliance tools and subprocessors that assist in automated control testing and report generation.\n\n2.2 All Client Data shall be stored and processed exclusively within the continental United States.\n\n2.3 Provider shall maintain AES-256 encryption at rest and in transit and appropriate administrative, physical, and technical safeguards per 45 C.F.R. Section 164.312."),
            ("3. SUBPROCESSORS", "3.1 Provider may engage subprocessors and third-party compliance tools upon fifteen (15) business days prior written notice to Client. Each subprocessor shall execute data protection agreements consistent with this Agreement.\n\n3.2 Provider shall maintain a current list of all subprocessors and make it available to Client upon request."),
            ("4. HIPAA COMPLIANCE", "4.1 Provider is a Business Associate under HIPAA (45 C.F.R. Parts 160 and 164). This Section constitutes a Business Associate Agreement per 45 C.F.R. Section 164.502(e) and Section 164.504(e).\n\n4.2 Provider shall not use or disclose PHI other than as permitted by this Agreement or required by law.\n\n4.3 Provider shall implement safeguards per Subpart C of 45 C.F.R. Part 164 including risk analysis, audit controls, access controls, and AES-256 encryption.\n\n4.4 Provider shall report any Breach of Unsecured PHI within thirty (30) calendar days.\n\n4.5 Subcontractors handling PHI shall execute Business Associate Agreements per 45 C.F.R. Section 164.504(e).\n\n4.6 Upon termination, Provider shall return or destroy all PHI within thirty (30) days."),
            ("5. CCPA COMPLIANCE", "5.1 Provider is a Service Provider per Cal. Civ. Code Section 1798.140(ag).\n\n5.2 Provider shall not sell or share Personal Information. Provider shall not use Personal Information for any purpose other than performing the Services or outside the direct business relationship.\n\n5.3 Provider shall assist Client with consumer requests within ten (10) business days.\n\n5.4 Upon termination, Provider shall delete all Personal Information within thirty (30) days."),
            ("6. FEES AND TERM", "6.1 Client shall pay Provider an annual fee of USD 120,000, invoiced quarterly.\n\n6.2 Initial term of two (2) years with automatic one-year renewals.\n\n6.3 Either party may terminate for material breach upon thirty (30) days written notice."),
        ],
    },
    {
        "filename": "clearledger_engagement.pdf",
        "title": "SOC 1 TYPE 2 ENGAGEMENT LETTER",
        "client": "ClearLedger, LLC",
        "sections": [
            ("ENGAGEMENT SERVICES", "This letter confirms the arrangements regarding the services CyberCompliance Inc. (\"Provider\") is to perform for ClearLedger, LLC (the \"Company\") related to its Sales Tax Service system (the \"Service Organization's System\"). Provider will perform an examination of the Service Organization's System in accordance with attestation standards established by the American Institute of Certified Public Accountants (\"AICPA\"), and in relation to the criteria stated in management's assertion. Provider will plan and perform such procedures as necessary to obtain reasonable assurance about whether management's description of the Service Organization's System fairly presents the system that was designed and implemented for the period October 1, 2024, to September 30, 2025.\n\nThe Company uses subservice organizations for tax payment processing and hosting services. Management's description includes the services provided by the subservice organizations, but the control objectives and related controls of those subservice organizations are not included in the scope of this engagement. At the conclusion of the examination, Provider will issue a written SOC 1, Type 2 report addressed to the management of the Company."),
            ("EXAMINATION SCOPE", "The examination involves performing procedures to obtain evidence about the fairness of the presentation of the description and the suitability of the design and operating effectiveness of controls. This includes:\n(a) Assessing the risks that management's description is not fairly presented and that controls were not suitably designed or operating effectively;\n(b) Testing the operating effectiveness of controls necessary to provide reasonable assurance that the related control objectives were achieved;\n(c) Evaluating the overall presentation of management's description and the suitability of the control objectives.\n\nThe examination does not include evaluating whether complementary user entity controls contemplated in the design of the Service Organization System's controls are suitably designed and operating effectively."),
            ("COMPANY RESPONSIBILITIES", "Management of the Service Organization is responsible for:\n(a) The operations of the Service Organization's System;\n(b) The assertion that the description fairly presents the system made available to user entities throughout the period;\n(c) The assertion that controls were suitably designed and operating effectively throughout the period;\n(d) Providing a written management representation letter;\n(e) Identifying and ensuring compliance with applicable laws and regulations;\n(f) Preparing the description and assertion, including completeness, accuracy and method of presentation;\n(g) Selecting criteria, specifying control objectives, and identifying risks that threaten their achievement;\n(h) Designing, implementing and documenting controls;\n(i) Providing unrestricted access to personnel, records, documentation, service-level agreements, and internal audit reports."),
            ("USE OF SUBCONTRACTORS AND THIRD-PARTY PRODUCTS", "Provider may use affiliates or qualified third-party service providers, located within or outside the United States, to assist in providing professional services. In such circumstances, it may be necessary to disclose Confidential Information and Personal Information to them. Provider may share Company information with subcontractors within or outside of the United States, provided that such recipients are bound by written obligations of confidentiality. The Company acknowledges that use of subcontractors may involve the processing, input, disclosure, movement, transfer, and storage of data outside of the United States and outside of Provider's technology infrastructure.\n\nProvider may provide services using certain third-party hardware, software, equipment or products (\"Third-Party Products\"). The Company acknowledges that the terms of use for such Third-Party Products, including applicable EULAs, will govern all obligations of the licensor relating to data privacy, storage, recovery, security and processing. The Company consents to the disclosure of its information to licensors of such Third-Party Products and acknowledges that such data may be collected, processed, stored, and used by licensors for benchmarking, analytics, and other business purposes in aggregate form only, without identifying the Company or any individual."),
            ("CONFIDENTIALITY", "\"Confidential Information\" means information in any form consisting of: (i) any nonpublic information provided by the disclosing party; (ii) any information identified as confidential; or (iii) any information that by its nature should be treated as confidential. Confidential Information does not include information that is publicly available, was lawfully in the receiving party's possession, is provided by a third party without restriction, or is independently developed.\n\nThe receiving party will treat Confidential Information with the same degree of care as its own, but no less than a reasonable standard of care. The receiving party will promptly notify the disclosing party of any use or disclosure in violation of this letter.\n\nThe Company consents to Provider using Confidential Information and Personal Information to: (i) improve the quality of services and offerings; and/or (ii) develop or perform internal data analysis, business analytics, or other internal insight generation. Provider will not use or disclose such information in a way that would permit the Company or an individual to be identified by third parties without prior written consent."),
            ("DATA PROTECTION AND PERSONAL INFORMATION", "\"Personal Information\" means any personal information or data, as defined by applicable privacy, data protection or cybersecurity laws, that directly or indirectly identifies a natural person. Each party agrees to transmit Personal Information consistent with applicable laws.\n\nThe Company represents and warrants that it has provided all notices and obtained all consents required under applicable data protection laws prior to collection, use and disclosure of Personal Information.\n\nTo the extent the California Consumer Privacy Act and California Privacy Rights Act (\"CCPA\") are applicable, Provider is a \"Service Provider\" as defined by the CCPA. For any Personal Information disclosed by the Company, Provider will not: (i) \"sell\" or \"share\" the PI as defined by the CCPA; (ii) retain, use, or disclose PI for any purpose other than the specific business purpose in this letter; or (iii) retain, use, or disclose the information outside of the direct business relationship between the parties unless to a subcontractor meeting CCPA \"Service Provider\" requirements.\n\nPrior to disclosing data to Provider, the Company will identify in writing any data subject to heightened protections under applicable statutes including HIPAA, NISPOM, controlled unclassified information (CUI), EAR, or ITAR. Unless expressly agreed in writing, the Company shall not disclose such data to Provider."),
            ("INDEMNIFICATION AND LIMITATION OF LIABILITY", "The Company agrees to indemnify, hold harmless and release Provider from all third-party claims, liabilities, losses and costs arising where there has been a knowing misrepresentation by Company management.\n\nNO CLAIM ARISING FROM THE SERVICES SHALL BE FILED MORE THAN TWO YEARS AFTER THE DATE OF THE EXAMINATION REPORT OR THE DATE OF THIS LETTER IF NO REPORT HAS BEEN ISSUED. IN NO EVENT SHALL EITHER PARTY BE LIABLE FOR INTERRUPTION OR LOSS OF BUSINESS, LOST PROFITS, SAVINGS, REVENUE, GOODWILL, SOFTWARE, HARDWARE OR DATA, OR INCIDENTAL, INDIRECT, PUNITIVE, CONSEQUENTIAL, SPECIAL OR EXEMPLARY DAMAGES. THE TOTAL AGGREGATE LIABILITY ARISING FROM THIS LETTER WILL NOT EXCEED THE TOTAL FEES PAID BY THE COMPANY UNDER THIS LETTER."),
            ("FEES", "Fees for the services described above are based upon the value of the services performed and time required. The fee for this engagement will be $105,000. Interim billings will be submitted as follows:\n\nInvoice 1 - Upon Execution: $60,000 plus expenses\nInvoice 2 - July 2025: $40,000 plus expenses\nInvoice 3 - October 2025: $5,000 plus expenses\n\nPayment is due within thirty (30) days of receipt. A charge of 5% of fees applies for indirect administrative expenses including technology, research, communications, and clerical assistance."),
            ("TERM AND TERMINATION", "Either party may terminate this letter for any reason upon fifteen (15) days prior written notice. In the event of termination, the Company will pay for all services rendered, expenses incurred and noncancelable commitments through the effective date. Either party may terminate upon written notice if continued performance would result in violation of law, regulatory requirements, or applicable professional or ethical standards.\n\nWhen engagement has been suspended at management's request and work has not recommenced within 120 days, Provider may terminate without further obligation. Resumption following termination will require a new engagement letter.\n\nThis letter will be governed by the laws of the state of Illinois, without regard to conflict of law principles."),
        ],
    },
    {
        "filename": "vantage_tech_sow.pdf",
        "title": "STATEMENT OF WORK - SOC 1 READINESS ASSESSMENT",
        "client": "Vantage Technologies LLC",
        "sections": [
            ("A. SERVICES AND SCOPE OF WORK", "This Statement of Work (\"SOW\") is entered into by and between Vantage Technologies LLC, a New York corporation (\"Vantage\") and CyberCompliance Inc. (\"Provider\") pursuant to the Master Services Agreement dated June 4, 2024 (the \"Agreement\"). This SOW is incorporated by reference into the Agreement.\n\nAs a result of recent changes to Vantage's claims processing systems, controls and systems have changed, which will impact the existing SOC 1 report. The scope of this engagement includes: identifying the current claims processing business process and information technology general controls; identifying control gaps and recommendations in accordance with AICPA control objectives and attestation standards; and reviewing Vantage's updates to the description of the service organization's system.\n\nProvider will interview control owners, observe processes and inspect documentation, including:\n(a) An updated description of the current system and associated controls;\n(b) Identifying potential control design gaps;\n(c) Identifying potential gaps related to evidence of controls operating effectively;\n(d) Documenting observations and high-level recommendations;\n(e) Reviewing Vantage's edits to the system description to fairly present the service organization's system.\n\nThe Services herein will not constitute an audit, review or compilation of financial statements, nor an external examination of internal control systems. No opinion or assurance on financial statements, internal controls or compliance will be expressed."),
            ("B. ENGAGEMENT TEAM", "Chris Kettering, Director, will be responsible for overseeing the engagement and delivery of Services. Hannah Gilbert, Manager, will coordinate all fieldwork and engagement communications. Other personnel at the necessary skill and experience levels may be called upon as appropriate. While Provider will attempt to comply with requests for certain individuals, Provider retains the right to assign and reassign personnel as appropriate."),
            ("C. THIRD-PARTY PRODUCTS", "Under this SOW, Provider may make available to Vantage or use in connection with the Services certain third-party software, hardware, equipment or products (\"Third-Party Products\"). Provider may also recommend that Vantage purchase, license or subscribe to a Third-Party Product. Vantage acknowledges that Provider's recommendation of a Third-Party Product is intended as a guideline only and that Vantage is solely responsible for the selection and decision to use such Third-Party Product."),
            ("D. VANTAGE RESPONSIBILITIES AND ACKNOWLEDGEMENTS", "Vantage's management acknowledges its responsibility for: (i) establishing and maintaining effective internal control over financial reporting and safeguarding assets; (ii) identifying and ensuring compliance with the Sarbanes-Oxley Act and other applicable laws; (iii) informing Provider of all significant deficiencies and material weaknesses in internal controls; and (iv) making all financial records and related information available to Provider.\n\nVantage will designate an employee within senior management to make or obtain all management decisions on a timely basis. Vantage will ensure Provider has access to personnel, facilities, computer systems, applications, equipment, and data deemed reasonably necessary to perform the Services.\n\nVantage agrees to provide information that can be relied on as accurate and complete. Provider will be entitled to rely on all of Vantage's decisions and approvals.\n\nVantage acknowledges that it has the ultimate responsibility for ensuring accuracy of materials generated by Provider and will carefully review all such materials. Provider shall not be liable for action reasonably taken in good faith in accordance with directions from Vantage.\n\nVantage acknowledges that: (i) it is responsible for maintaining all original data, records and information; (ii) Provider is not providing backup services; (iii) Provider is not responsible for maintaining data provided by Vantage; and (iv) Provider is not responsible for maintaining any deliverables, reports or work product on Vantage's behalf."),
            ("E. DATA HANDLING AND PRIVACY", "Use of information to provide services: Vantage consents to Provider using any information or data, including confidential, personal or other protected information, provided by or on behalf of Vantage, in connection with: (i) the Services under this SOW to provide professional services under any other agreement with Vantage; and (ii) professional services under another agreement with Vantage to provide Services under this SOW.\n\nEnhancement of services and insight generation: Vantage consents to Provider utilizing Vantage confidential information and personal information to: (i) improve the quality of services and offerings; and/or (ii) develop or perform internal data analysis, business analytics or insights. Information developed for these purposes may be used or disclosed to current or prospective clients. Provider will not use or disclose such information in a way that would permit Vantage or an individual to be identified by a third party without prior written consent.\n\nVantage is solely responsible for managing and maintaining its IT and cybersecurity protocols and the requirements with respect to access provided to Provider. Vantage shall only provide access to information and data reasonably necessary for Provider to perform the Services."),
            ("F. INFORMATION SECURITY ACKNOWLEDGEMENT", "Vantage acknowledges that no IT security assessment can ever provide total assurance against potential security intrusions. The effectiveness of controls and security measures is subject to inherent limitations, and all errors or problems may not be detected. Assessment results are subject to the risk that changes are made to systems or controls, changes are made in processing requirements, changes are required because of the passage of time, or new technology is developed. Provider is not responsible for Vantage's lack of specific controls, a breach of security, or other errors or fraud related to any part of Vantage's systems."),
            ("G. FEES AND EXPENSES", "Fees for the Services will be based upon a fixed fee with the estimated level of effort based upon the scoping details provided by Vantage Technologies LLC.\n\nBilling Schedule:\nAugust 30, 2025: $15,000\nOctober 31, 2025: $15,000\nTotal: $30,000\n\nOut-of-pocket expenses, including travel related expenses for airlines, hotels, meals, and transportation, will be billed at actual cost as incurred. Mileage driven in personally-owned vehicles will be billed based on the current IRS published rate. Airline travel shall be booked at coach or economy class rates. Hotel rooms will be booked at reasonably priced hotels and at corporate rates if available.\n\nProvider will communicate travel plans to Vantage in advance and obtain pre-approval in writing (email is sufficient) before incurring expenses.\n\nIn the event this SOW is terminated before completion, Vantage will pay a portion of the fixed fees based upon the proportion of work performed. These fees are exclusive of any expenses and taxes."),
            ("H. LIMITATION OF LIABILITY AND GOVERNING LAW", "IN NO EVENT SHALL EITHER PARTY BE LIABLE FOR INTERRUPTION OR LOSS OF BUSINESS, LOST PROFITS, SAVINGS, REVENUE, GOODWILL, OR INCIDENTAL, INDIRECT, PUNITIVE, CONSEQUENTIAL, SPECIAL OR EXEMPLARY DAMAGES, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE TOTAL AGGREGATE LIABILITY OF EITHER PARTY ARISING FROM THIS SOW WILL NOT EXCEED THE TOTAL FEES PAID UNDER THIS SOW.\n\nThis SOW, including its validity, interpretation, construction and enforceability, will be governed by the laws of the State of New York, without regard to conflict of law principles, and applicable U.S. federal law.\n\nEither party may terminate this SOW upon written notice if circumstances arise that would cause continued performance to result in violation of law, regulatory requirements, contractual obligations, or applicable professional or ethical standards."),
        ],
    },
    {
        "filename": "compliance_first_msa.pdf",
        "title": "MASTER SERVICES AGREEMENT",
        "client": "ComplianceFirst Inc.",
        "sections": [
            ("1. DEFINITIONS", '"Protected Health Information" or "PHI" shall have the same meaning as the term "protected health information" in 45 C.F.R. Section 160.103, limited to information created, received, maintained, or transmitted by Provider on behalf of Client. "Personal Information" shall have the meaning set forth in Cal. Civ. Code Section 1798.140(v) as amended by the CCPA/CPRA. "Business Associate" and "Service Provider" shall have the meanings set forth in HIPAA (45 C.F.R. Parts 160 and 164) and CCPA (Cal. Civ. Code Section 1798.140(ag)), respectively.'),
            ("2. SERVICES", "Provider shall deliver compliance assessment, monitoring, and advisory services as described in the applicable Statement of Work. Provider may engage qualified third-party vendors and subprocessors to assist in delivering the Services, subject to Section 3."),
            ("3. DATA HANDLING AND SUBPROCESSORS", "3.1 Provider shall process Client Data solely for the purpose of providing the Services. Provider shall not use Client Data for any secondary purpose, including internal analytics, benchmarking, or product improvement.\n\n3.2 All Client Data shall be stored and processed exclusively within data centers located in the continental United States.\n\n3.3 Provider may engage subprocessors upon fifteen (15) business days' prior written notice to Client. Client may object in writing during the notice period; absent timely objection, approval is deemed granted. Each subprocessor shall execute a Business Associate Agreement per 45 C.F.R. Section 164.504(e) and a CCPA-compliant service provider agreement containing data protection obligations equivalent to this Agreement, and shall process data exclusively within the continental United States."),
            ("4. HIPAA BUSINESS ASSOCIATE AGREEMENT", '4.1 To the extent Provider creates, receives, maintains, or transmits PHI on behalf of Client, Provider is a "Business Associate" as defined under HIPAA. This Section constitutes a Business Associate Agreement per 45 C.F.R. Section 164.502(e) and Section 164.504(e).\n\n4.2 Provider shall not use or disclose PHI other than as permitted by this Agreement or as required by law. Permitted uses are limited to: (a) performance of the Services; (b) Provider\'s proper management and administration where required by law.\n\n4.3 Provider shall implement administrative, physical, and technical safeguards per Subpart C of 45 C.F.R. Part 164, including: risk analysis (Section 164.308(a)(1)), audit controls (Section 164.312(b)), access controls (Section 164.312(a)), and AES-256 encryption at rest and in transit.\n\n4.4 Provider shall report any Breach of Unsecured PHI (45 C.F.R. Section 164.402) or Security Incident to Client within thirty (30) calendar days of discovery, including: (a) identification of affected individuals; (b) description of the incident; (c) types of PHI involved; (d) recommended protective steps; (e) corrective actions taken.\n\n4.5 Provider shall ensure subcontractors handling PHI execute Business Associate Agreements with identical restrictions per 45 C.F.R. Section 164.504(e)(1)(ii)(B).\n\n4.6 Provider shall support Client\'s obligations for individual access (45 C.F.R. Section 164.524), amendment (Section 164.526), and accounting of disclosures (Section 164.528) within fifteen (15) business days of request.\n\n4.7 Provider shall make its practices and records available to the Secretary of HHS for compliance determination.\n\n4.8 Upon termination, Provider shall return or destroy all PHI within thirty (30) calendar days and certify destruction in writing. If infeasible, protections extend to retained PHI indefinitely.'),
            ("5. CCPA SERVICE PROVIDER OBLIGATIONS", '5.1 To the extent Provider processes Personal Information subject to the CCPA, Provider is a "Service Provider" per Cal. Civ. Code Section 1798.140(ag).\n\n5.2 Provider certifies: (a) Provider shall not sell or share Personal Information as defined by the CCPA; (b) Provider shall not retain, use, or disclose Personal Information for any purpose other than performing the Services; (c) Provider shall not retain, use, or disclose Personal Information outside the direct business relationship between Provider and Client; (d) Provider shall not combine Personal Information with information from other sources except as permitted by Cal. Civ. Code Section 1798.140(e)(6) (security incident detection) and (e)(7) (service quality improvement for Client only).\n\n5.3 Provider shall assist Client in responding to verifiable consumer requests (know, access, delete, correct) within ten (10) business days and direct subprocessors to comply. Retention is permitted only under Cal. Civ. Code Section 1798.105(d).\n\n5.4 Provider shall notify Client within five (5) business days if it can no longer meet CCPA obligations. Client may take reasonable steps to remediate unauthorized use.\n\n5.5 Provider shall allow compliance audits not more than once per twelve (12) months.\n\n5.6 Upon termination, Provider shall delete all Personal Information within thirty (30) calendar days and certify deletion in writing.'),
            ("6. CONFIDENTIALITY", "Each party shall maintain the confidentiality of the other party's Confidential Information and shall not disclose it to any third party except as required by law or as necessary to perform obligations under this Agreement. The receiving party may disclose Confidential Information to employees, contractors, and authorized subprocessors who are bound by confidentiality obligations no less restrictive than this Section."),
            ("7. FEES AND TERM", "7.1 Client shall pay Provider an annual fee of $75,000, invoiced quarterly in advance. Payment is due within thirty (30) days of invoice.\n\n7.2 This Agreement has an initial term of two (2) years, automatically renewing for successive one-year periods unless either party provides sixty (60) days' written notice of non-renewal.\n\n7.3 Either party may terminate for material breach upon thirty (30) days' written notice if the breach is not cured within the notice period. Client may terminate immediately if Provider breaches Section 4 (HIPAA) and cure is not feasible per 45 C.F.R. Section 164.504(e)(1)(ii).\n\n7.4 This Agreement shall be governed by the laws of the State of California."),
        ],
    },
]


def create_contract_pdf(contract: dict) -> None:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Title
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, contract["title"], new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(5)

    # Between clause
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Between: {contract['client']} (\"Client\")", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, "And: CyberCompliance Inc. (\"Provider\")", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Effective Date: January 1, 2024", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # Sections
    for heading, body in contract["sections"]:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 8, heading, new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 5, body)
        pdf.ln(4)

    # Signature block
    pdf.ln(10)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, "IN WITNESS WHEREOF, the parties have executed this Agreement.", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)
    pdf.cell(90, 6, "____________________________", new_x="RIGHT", new_y="LAST")
    pdf.cell(90, 6, "____________________________", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(90, 6, f"{contract['client']}", new_x="RIGHT", new_y="LAST")
    pdf.cell(90, 6, "CyberCompliance Inc.", new_x="LMARGIN", new_y="NEXT")

    filepath = os.path.join(CONTRACTS_DIR, contract["filename"])
    pdf.output(filepath)
    print(f"  Created: {filepath}")


if __name__ == "__main__":
    print("Generating sample contracts...")
    for contract in CONTRACTS:
        create_contract_pdf(contract)
    print(f"Done! {len(CONTRACTS)} contracts created in {CONTRACTS_DIR}")
