"""Generate sample contract PDFs for ContractSwarm demo."""

from fpdf import FPDF
import os

CONTRACTS_DIR = os.path.join(os.path.dirname(__file__), "..", "contracts")
os.makedirs(CONTRACTS_DIR, exist_ok=True)

CONTRACTS = [
    {
        "filename": "acme_corp_msa.pdf",
        "title": "MASTER SERVICES AGREEMENT",
        "client": "Acme Corporation",
        "sections": [
            ("1. DEFINITIONS", '"Confidential Information" means any non-public information disclosed by either party to the other, whether orally or in writing, that is designated as confidential or that reasonably should be understood to be confidential given the nature of the information and the circumstances of disclosure.'),
            ("2. SERVICES", "Provider shall deliver cybersecurity compliance monitoring services as described in Exhibit A. Provider shall maintain SOC 2 Type II certification throughout the term of this Agreement."),
            ("3. DATA HANDLING", "3.1 Provider shall process Client Data solely for the purpose of providing the Services. Provider shall not transfer, share, or disclose Client Data to any third party without the prior written consent of Client.\n\n3.2 All Client Data shall be stored exclusively within the continental United States. Provider shall not transfer Client Data to any facility, server, or data center located outside the United States without prior written approval from Client."),
            ("4. SUBPROCESSORS", "4.1 Provider shall not engage any subprocessor to process Client Data without obtaining Client's prior written consent. Client shall have the right to object to any proposed subprocessor within thirty (30) days of notification.\n\n4.2 Provider shall maintain a current list of all subprocessors and make it available to Client upon request."),
            ("5. EXCLUSIVITY", "During the term of this Agreement, Client shall not engage any other vendor to provide substantially similar cybersecurity compliance monitoring services. This exclusivity provision shall survive for twelve (12) months following termination."),
            ("6. LIABILITY", "6.1 Provider's total aggregate liability under this Agreement shall not exceed the total fees paid by Client in the twelve (12) months preceding the claim.\n\n6.2 Neither party shall be liable for any indirect, incidental, special, consequential, or punitive damages."),
            ("7. TERM AND TERMINATION", "7.1 This Agreement shall have an initial term of three (3) years, automatically renewing for successive one-year periods unless either party provides ninety (90) days' written notice of non-renewal.\n\n7.2 Either party may terminate this Agreement immediately upon written notice if the other party materially breaches this Agreement and fails to cure such breach within thirty (30) days."),
        ],
    },
    {
        "filename": "globex_dpa.pdf",
        "title": "DATA PROCESSING AGREEMENT",
        "client": "Globex Industries",
        "sections": [
            ("1. SCOPE", "This Data Processing Agreement governs the processing of personal data by Provider on behalf of Client in connection with the cybersecurity services described in the Master Services Agreement dated January 15, 2024."),
            ("2. DATA CATEGORIES", "Provider shall process the following categories of personal data: employee names, email addresses, IP addresses, network access logs, device identifiers, and security event data."),
            ("3. PROCESSING RESTRICTIONS", "3.1 Provider shall process personal data only on documented instructions from Client, including with regard to transfers of personal data to a third country.\n\n3.2 Provider shall ensure that persons authorized to process the personal data have committed themselves to confidentiality.\n\n3.3 Provider shall not engage another processor without prior specific written authorization of Client. Where Provider engages another processor, it shall impose the same data protection obligations as set out in this Agreement."),
            ("4. DATA TRANSFERS", "4.1 Provider shall not transfer personal data to any country outside the European Economic Area without appropriate safeguards as required by GDPR Article 46.\n\n4.2 Client acknowledges that Provider's primary data centers are located in the United States and the European Union."),
            ("5. SECURITY MEASURES", "Provider shall implement appropriate technical and organizational measures to ensure a level of security appropriate to the risk, including:\n(a) pseudonymization and encryption of personal data;\n(b) the ability to ensure ongoing confidentiality and integrity;\n(c) the ability to restore availability and access to personal data in a timely manner;\n(d) a process for regularly testing and evaluating effectiveness of security measures."),
            ("6. BREACH NOTIFICATION", "Provider shall notify Client without undue delay after becoming aware of a personal data breach. Such notification shall include: (a) the nature of the breach; (b) the categories and approximate number of data subjects concerned; (c) the likely consequences of the breach; (d) the measures taken or proposed to address the breach."),
            ("7. AUDIT RIGHTS", "Provider shall make available to Client all information necessary to demonstrate compliance with this Agreement and allow for and contribute to audits conducted by Client or an auditor mandated by Client."),
        ],
    },
    {
        "filename": "initech_services.pdf",
        "title": "SERVICE AGREEMENT",
        "client": "Initech Solutions",
        "sections": [
            ("1. SERVICES DESCRIPTION", "Provider shall provide continuous security monitoring, vulnerability assessment, and compliance reporting services for Client's cloud infrastructure as described in Schedule 1."),
            ("2. CONFIDENTIALITY", "2.1 Each party agrees to maintain the confidentiality of the other party's Confidential Information and not to disclose such information to any third party.\n\n2.2 The receiving party may disclose Confidential Information to its employees, contractors, and agents who need to know such information and who are bound by confidentiality obligations no less restrictive than those contained herein."),
            ("3. INTELLECTUAL PROPERTY", "3.1 All intellectual property rights in the Services and any deliverables shall remain with Provider.\n\n3.2 Client retains all rights to Client Data. Provider is granted a limited, non-exclusive license to use Client Data solely for the purpose of providing the Services."),
            ("4. DATA PROCESSING", "4.1 Provider may engage third-party service providers to assist in delivering the Services, provided that any such third party agrees to substantially similar data protection obligations.\n\n4.2 Provider shall process Client Data in accordance with applicable data protection laws, including but not limited to the California Consumer Privacy Act (CCPA).\n\n4.3 Client Data may be processed in any data center operated by Provider or its approved subprocessors, which currently include facilities in the United States, Canada, and the European Union."),
            ("5. COMPLIANCE", "Provider shall maintain compliance with SOC 2 Type II, ISO 27001, and applicable industry regulations throughout the term of this Agreement."),
            ("6. LIMITATION OF LIABILITY", "PROVIDER'S TOTAL LIABILITY SHALL NOT EXCEED TWO TIMES (2X) THE ANNUAL FEES PAID UNDER THIS AGREEMENT. IN NO EVENT SHALL EITHER PARTY BE LIABLE FOR LOST PROFITS, LOSS OF DATA, OR CONSEQUENTIAL DAMAGES."),
            ("7. GOVERNING LAW", "This Agreement shall be governed by and construed in accordance with the laws of the State of California, without regard to its conflict of laws provisions."),
        ],
    },
    {
        "filename": "clearledger_engagement.pdf",
        "title": "SOC 1 TYPE 2 ENGAGEMENT LETTER",
        "client": "ClearLedger, LLC",
        "sections": [
            ("ENGAGEMENT SERVICES", "This letter confirms the arrangements regarding the services CyberCompliance Inc. (\"Provider\") is to perform for ClearLedger, LLC (the \"Company\") related to its Sales Tax Service system (the \"Service Organization's System\"). Provider will perform an examination of the Service Organization's System in accordance with attestation standards established by the American Institute of Certified Public Accountants (\"AICPA\"), and in relation to the criteria stated in management's assertion. Provider will plan and perform such procedures as necessary to obtain reasonable assurance about whether management's description of the Service Organization's System fairly presents the system that was designed and implemented for the period October 1, 2024, to September 30, 2025.\n\nThe Company uses subservice organizations for tax payment processing and hosting services. Management's description includes the services provided by the subservice organizations, but the control objectives and related controls of those subservice organizations are not included in the scope of this engagement. At the conclusion of the examination, Provider will issue a written SOC 1, Type 2 report addressed to the management of the Company."),
            ("EXAMINATION SCOPE", "The examination involves performing procedures to obtain evidence about the fairness of the presentation of the description and the suitability of the design and operating effectiveness of controls. This includes:\n(a) Assessing the risks that management's description is not fairly presented and that controls were not suitably designed or operating effectively;\n(b) Testing the operating effectiveness of controls necessary to provide reasonable assurance that the related control objectives were achieved;\n(c) Evaluating the overall presentation of management's description and the suitability of the control objectives.\n\nThe examination does not include evaluating whether complementary user entity controls contemplated in the design of the Service Organization System's controls are suitably designed and operating effectively."),
            ("COMPANY RESPONSIBILITIES", "Management of the Service Organization is responsible for:\n(a) The operations of the Service Organization's System;\n(b) The assertion that the description fairly presents the system made available to user entities throughout the period;\n(c) The assertion that controls were suitably designed and operating effectively throughout the period;\n(d) Providing a written management representation letter;\n(e) Identifying and ensuring compliance with applicable laws and regulations;\n(f) Preparing the description and assertion, including completeness, accuracy and method of presentation;\n(g) Selecting criteria, specifying control objectives, and identifying risks that threaten their achievement;\n(h) Designing, implementing and documenting controls;\n(i) Providing unrestricted access to personnel, records, documentation, service-level agreements, and internal audit reports."),
            ("USE OF SUBCONTRACTORS AND THIRD-PARTY PRODUCTS", "Provider may use affiliates or qualified third-party service providers, located within or outside the United States, to assist in providing professional services. In such circumstances, it may be necessary to disclose Confidential Information and Personal Information to them. Provider may share Company information with subcontractors within or outside of the United States, provided that such recipients are bound by written obligations of confidentiality. The Company acknowledges that use of subcontractors may involve the processing, input, disclosure, movement, transfer, and storage of data outside of the United States and outside of Provider's technology infrastructure.\n\nProvider may provide services using certain third-party hardware, software, equipment or products (\"Third-Party Products\"). The Company acknowledges that the terms of use for such Third-Party Products, including applicable EULAs, will govern all obligations of the licensor relating to data privacy, storage, recovery, security and processing. The Company consents to the disclosure of its information to licensors of such Third-Party Products and acknowledges that such data may be collected, processed, stored, and used by licensors for benchmarking, analytics, and other business purposes in aggregate form only, without identifying the Company or any individual."),
            ("CONFIDENTIALITY", "\"Confidential Information\" means information in any form consisting of: (i) any nonpublic information provided by the disclosing party; (ii) any information identified as confidential; or (iii) any information that by its nature should be treated as confidential. Confidential Information does not include information that is publicly available, was lawfully in the receiving party's possession, is provided by a third party without restriction, or is independently developed.\n\nThe receiving party will treat Confidential Information with the same degree of care as its own, but no less than a reasonable standard of care. The receiving party will promptly notify the disclosing party of any use or disclosure in violation of this letter.\n\nThe Company consents to Provider using Confidential Information and Personal Information to: (i) improve the quality of services and offerings; and/or (ii) develop or perform internal data analysis, business analytics, or other internal insight generation. Provider will not use or disclose such information in a way that would permit the Company or an individual to be identified by third parties without prior written consent."),
            ("DATA PROTECTION AND PERSONAL INFORMATION", "\"Personal Information\" means any personal information or data, as defined by applicable privacy, data protection or cybersecurity laws, that directly or indirectly identifies a natural person. Each party agrees to transmit Personal Information consistent with applicable laws.\n\nThe Company represents and warrants that it has provided all notices and obtained all consents required under applicable data protection laws prior to collection, use and disclosure of Personal Information.\n\nTo the extent the California Consumer Privacy Act and California Privacy Rights Act (\"CCPA\") are applicable, Provider is a \"Service Provider\" as defined by the CCPA. For any Personal Information disclosed by the Company, Provider will not: (i) \"sell\" or \"share\" the PI as defined by the CCPA; (ii) retain, use, or disclose PI for any purpose other than the specific business purpose in this letter; or (iii) retain, use, or disclose the information outside of the direct business relationship between the parties unless to a subcontractor meeting CCPA \"Service Provider\" requirements.\n\nPrior to disclosing data to Provider, the Company will identify in writing any data subject to heightened protections under applicable statutes including HIPAA, NISPOM, controlled unclassified information (CUI), EAR, or ITAR. Unless expressly agreed in writing, the Company shall not disclose such data to Provider."),
            ("INDEMNIFICATION AND LIMITATION OF LIABILITY", "The Company agrees to indemnify, hold harmless and release Provider from all third-party claims, liabilities, losses and costs arising where there has been a knowing misrepresentation by Company management.\n\nNO CLAIM ARISING FROM THE SERVICES SHALL BE FILED MORE THAN TWO YEARS AFTER THE DATE OF THE EXAMINATION REPORT OR THE DATE OF THIS LETTER IF NO REPORT HAS BEEN ISSUED. IN NO EVENT SHALL EITHER PARTY BE LIABLE FOR INTERRUPTION OR LOSS OF BUSINESS, LOST PROFITS, SAVINGS, REVENUE, GOODWILL, SOFTWARE, HARDWARE OR DATA, OR INCIDENTAL, INDIRECT, PUNITIVE, CONSEQUENTIAL, SPECIAL OR EXEMPLARY DAMAGES. THE TOTAL AGGREGATE LIABILITY ARISING FROM THIS LETTER WILL NOT EXCEED THE TOTAL FEES PAID BY THE COMPANY UNDER THIS LETTER."),
            ("FEES", "Fees for the services described above are based upon the value of the services performed and time required. The fee for this engagement will be $105,000. Interim billings will be submitted as follows:\n\nInvoice 1 - Upon Execution: $60,000 plus expenses\nInvoice 2 - July 2025: $40,000 plus expenses\nInvoice 3 - October 2025: $5,000 plus expenses\n\nPayment is due within thirty (30) days of receipt. A charge of 5% of fees applies for indirect administrative expenses including technology, research, communications, and clerical assistance."),
            ("TERM AND TERMINATION", "Either party may terminate this letter for any reason upon fifteen (15) days prior written notice. In the event of termination, the Company will pay for all services rendered, expenses incurred and noncancelable commitments through the effective date. Either party may terminate upon written notice if continued performance would result in violation of law, regulatory requirements, or applicable professional or ethical standards.\n\nWhen engagement has been suspended at management's request and work has not recommenced within 120 days, Provider may terminate without further obligation. Resumption following termination will require a new engagement letter.\n\nThis letter will be governed by the laws of the state of Illinois, without regard to conflict of law principles."),
        ],
    },
    {
        "filename": "vantage_tech_sow.pdf",
        "title": "STATEMENT OF WORK - SOC 1 READINESS ASSESSMENT",
        "client": "Vantage Technologies LLC",
        "sections": [
            ("A. SERVICES AND SCOPE OF WORK", "This Statement of Work (\"SOW\") is entered into by and between Vantage Technologies LLC, a New York corporation (\"Vantage\") and CyberCompliance Inc. (\"Provider\") pursuant to the Master Services Agreement dated June 4, 2024 (the \"Agreement\"). This SOW is incorporated by reference into the Agreement.\n\nAs a result of recent changes to Vantage's claims processing systems, controls and systems have changed, which will impact the existing SOC 1 report. The scope of this engagement includes: identifying the current claims processing business process and information technology general controls; identifying control gaps and recommendations in accordance with AICPA control objectives and attestation standards; and reviewing Vantage's updates to the description of the service organization's system.\n\nProvider will interview control owners, observe processes and inspect documentation, including:\n(a) An updated description of the current system and associated controls;\n(b) Identifying potential control design gaps;\n(c) Identifying potential gaps related to evidence of controls operating effectively;\n(d) Documenting observations and high-level recommendations;\n(e) Reviewing Vantage's edits to the system description to fairly present the service organization's system.\n\nThe Services herein will not constitute an audit, review or compilation of financial statements, nor an external examination of internal control systems. No opinion or assurance on financial statements, internal controls or compliance will be expressed."),
            ("B. ENGAGEMENT TEAM", "Chris Kettering, Director, will be responsible for overseeing the engagement and delivery of Services. Hannah Gilbert, Manager, will coordinate all fieldwork and engagement communications. Other personnel at the necessary skill and experience levels may be called upon as appropriate. While Provider will attempt to comply with requests for certain individuals, Provider retains the right to assign and reassign personnel as appropriate."),
            ("C. THIRD-PARTY PRODUCTS", "Under this SOW, Provider may make available to Vantage or use in connection with the Services certain third-party software, hardware, equipment or products (\"Third-Party Products\"). Provider may also recommend that Vantage purchase, license or subscribe to a Third-Party Product. Vantage acknowledges that Provider's recommendation of a Third-Party Product is intended as a guideline only and that Vantage is solely responsible for the selection and decision to use such Third-Party Product."),
            ("D. VANTAGE RESPONSIBILITIES AND ACKNOWLEDGEMENTS", "Vantage's management acknowledges its responsibility for: (i) establishing and maintaining effective internal control over financial reporting and safeguarding assets; (ii) identifying and ensuring compliance with the Sarbanes-Oxley Act and other applicable laws; (iii) informing Provider of all significant deficiencies and material weaknesses in internal controls; and (iv) making all financial records and related information available to Provider.\n\nVantage will designate an employee within senior management to make or obtain all management decisions on a timely basis. Vantage will ensure Provider has access to personnel, facilities, computer systems, applications, equipment, and data deemed reasonably necessary to perform the Services.\n\nVantage agrees to provide information that can be relied on as accurate and complete. Provider will be entitled to rely on all of Vantage's decisions and approvals.\n\nVantage acknowledges that it has the ultimate responsibility for ensuring accuracy of materials generated by Provider and will carefully review all such materials. Provider shall not be liable for action reasonably taken in good faith in accordance with directions from Vantage.\n\nVantage acknowledges that: (i) it is responsible for maintaining all original data, records and information; (ii) Provider is not providing backup services; (iii) Provider is not responsible for maintaining data provided by Vantage; and (iv) Provider is not responsible for maintaining any deliverables, reports or work product on Vantage's behalf."),
            ("E. DATA HANDLING AND PRIVACY", "Use of information to provide services: Vantage consents to Provider using any information or data, including confidential, personal or other protected information, provided by or on behalf of Vantage, in connection with: (i) the Services under this SOW to provide professional services under any other agreement with Vantage; and (ii) professional services under another agreement with Vantage to provide Services under this SOW.\n\nEnhancement of services and insight generation: Vantage consents to Provider utilizing Vantage confidential information and personal information to: (i) improve the quality of services and offerings; and/or (ii) develop or perform internal data analysis, business analytics or insights. Information developed for these purposes may be used or disclosed to current or prospective clients. Provider will not use or disclose such information in a way that would permit Vantage or an individual to be identified by a third party without prior written consent.\n\nVantage is solely responsible for managing and maintaining its IT and cybersecurity protocols and the requirements with respect to access provided to Provider. Vantage shall only provide access to information and data reasonably necessary for Provider to perform the Services."),
            ("F. INFORMATION SECURITY ACKNOWLEDGEMENT", "Vantage acknowledges that no IT security assessment can ever provide total assurance against potential security intrusions. The effectiveness of controls and security measures is subject to inherent limitations, and all errors or problems may not be detected. Assessment results are subject to the risk that changes are made to systems or controls, changes are made in processing requirements, changes are required because of the passage of time, or new technology is developed. Provider is not responsible for Vantage's lack of specific controls, a breach of security, or other errors or fraud related to any part of Vantage's systems."),
            ("G. FEES AND EXPENSES", "Fees for the Services will be based upon a fixed fee with the estimated level of effort based upon the scoping details provided by Vantage Technologies LLC.\n\nBilling Schedule:\nAugust 30, 2025: $15,000\nOctober 31, 2025: $15,000\nTotal: $30,000\n\nOut-of-pocket expenses, including travel related expenses for airlines, hotels, meals, and transportation, will be billed at actual cost as incurred. Mileage driven in personally-owned vehicles will be billed based on the current IRS published rate. Airline travel shall be booked at coach or economy class rates. Hotel rooms will be booked at reasonably priced hotels and at corporate rates if available.\n\nProvider will communicate travel plans to Vantage in advance and obtain pre-approval in writing (email is sufficient) before incurring expenses.\n\nIn the event this SOW is terminated before completion, Vantage will pay a portion of the fixed fees based upon the proportion of work performed. These fees are exclusive of any expenses and taxes."),
            ("H. LIMITATION OF LIABILITY AND GOVERNING LAW", "IN NO EVENT SHALL EITHER PARTY BE LIABLE FOR INTERRUPTION OR LOSS OF BUSINESS, LOST PROFITS, SAVINGS, REVENUE, GOODWILL, OR INCIDENTAL, INDIRECT, PUNITIVE, CONSEQUENTIAL, SPECIAL OR EXEMPLARY DAMAGES, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE TOTAL AGGREGATE LIABILITY OF EITHER PARTY ARISING FROM THIS SOW WILL NOT EXCEED THE TOTAL FEES PAID UNDER THIS SOW.\n\nThis SOW, including its validity, interpretation, construction and enforceability, will be governed by the laws of the State of New York, without regard to conflict of law principles, and applicable U.S. federal law.\n\nEither party may terminate this SOW upon written notice if circumstances arise that would cause continued performance to result in violation of law, regulatory requirements, contractual obligations, or applicable professional or ethical standards."),
        ],
    },
]


def create_contract_pdf(contract: dict) -> None:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Title
    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, contract["title"], new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(5)

    # Between clause
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Between: {contract['client']} (\"Client\")", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, "And: CyberCompliance Inc. (\"Provider\")", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Effective Date: January 1, 2024", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    # Sections
    for heading, body in contract["sections"]:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 8, heading, new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        pdf.multi_cell(0, 5, body)
        pdf.ln(4)

    # Signature block
    pdf.ln(10)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, "IN WITNESS WHEREOF, the parties have executed this Agreement.", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)
    pdf.cell(90, 6, "____________________________", new_x="RIGHT", new_y="LAST")
    pdf.cell(90, 6, "____________________________", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(90, 6, f"{contract['client']}", new_x="RIGHT", new_y="LAST")
    pdf.cell(90, 6, "CyberCompliance Inc.", new_x="LMARGIN", new_y="NEXT")

    filepath = os.path.join(CONTRACTS_DIR, contract["filename"])
    pdf.output(filepath)
    print(f"  Created: {filepath}")


if __name__ == "__main__":
    print("Generating sample contracts...")
    for contract in CONTRACTS:
        create_contract_pdf(contract)
    print(f"Done! {len(CONTRACTS)} contracts created in {CONTRACTS_DIR}")
